spring:
  datasource:
    url: jdbc:h2:mem:db1;MODE=MySql;DB_CLOSE_DELAY=-1
    username: sa
    password:
    driverClassName: org.h2.Driver
  jpa:
    database: mysql
    hibernate:
      ddl-auto: create
    show-sql: true
  h2:
    console:
      enabled: true
logging:
  level:
    org.springframework.data: warn
    it.ozimov: debug
    h2: debug
    io.lhysin: debug
#    com.github.sonus21: ERROR