spring:
  datasource:
    url: jdbc:h2:mem:db1;MODE=PostgreSQL
    username: sa
    password:
    driverClassName: org.h2.Driver
  jpa:
    database: postgresql
    hibernate:
      ddl-auto: create
    show-sql: true

logging:
  level:
    h2: debug